### ISSUE TITLE
플랫폼 별 이미지 비율 리스트 추가

### ISSUE THREAD

**Issue by do0ori** [do0ori/image-ratio-padder-vanilla#1]
# 🤔Problem
- velog의 썸네일 이미지 비율이 1.91:1이라는 사실은 개발자 도구에서 탐색해서 확인할 수 있지만 일반 유저가 이 사실을 알기는 힘들다.
- 원하는 플랫폼의 이미지 비율은 따로 찾아서 입력해야 하기 때문에 번거롭다.

# 💡Idea
- 유명한 플랫폼들의 이미지 비율을 리스트 형태로 제공하고 사용자가 선택해서 사용할 수 있도록 한다.

# 📝Tasks
- [x] 어디에 리스트를 배치할지 디자인 고민해보기
- [ ] 리스트 요소 정하기 (velog, youtube 등)
- [ ] 리스트 만들기
- [ ] 추가된 기능을 README.md에 반영

**Comment by do0ori** [comment]
Resolved in https://github.com/do0ori/image-ratio-padder/pull/2
